# Copyright (c) 2026-present Arribada Initiative and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

from django.urls import path

from .views import (
    AdoptIssuesEndpoint,
    GithubInboxEndpoint,
    ProjectBlueprintEndpoint,
    ProjectCleanEndpoint,
    ProjectSetupApplyEndpoint,
    ProjectSetupPlanEndpoint,
    HubProjectsEndpoint,
    MyWorkEndpoint,
    ProjectAiPlanEndpoint,
    ProjectApplyPlanEndpoint,
    ProjectOverviewEndpoint,
    ProjectStatusEndpoint,
    ProjectTeamEndpoint,
    ProjectTemplateCloneEndpoint,
    TeamSyncEndpoint,
    WorkloadEndpoint,
    WorkspaceAiSettingsEndpoint,
    WorkspaceCriticalPathEndpoint,
    WorkspaceProjectStatusesEndpoint,
    PortfolioEndpoint,
    PortfolioItemsEndpoint,
    ProjectWikiDocEndpoint,
    ProjectAutoScheduleEndpoint,
    ProjectBaselineEndpoint,
    ProjectCriticalPathEndpoint,
    ProjectFolderAssignEndpoint,
    ProjectFolderDetailEndpoint,
    ProjectFoldersEndpoint,
    ProjectProgressEndpoint,
    ProjectRelationsEndpoint,
    ProjectScheduleEndpoint,
)

urlpatterns = [
    path(
        "workspaces/<str:slug>/portfolio/",
        PortfolioEndpoint.as_view(),
        name="arribada-portfolio",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/items/",
        PortfolioItemsEndpoint.as_view(),
        name="arribada-portfolio-items",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/schedule/",
        ProjectScheduleEndpoint.as_view(),
        name="arribada-project-schedule",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/relations/",
        ProjectRelationsEndpoint.as_view(),
        name="arribada-project-relations",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/progress/",
        ProjectProgressEndpoint.as_view(),
        name="arribada-project-progress",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/baseline/",
        ProjectBaselineEndpoint.as_view(),
        name="arribada-project-baseline",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/auto-schedule/",
        ProjectAutoScheduleEndpoint.as_view(),
        name="arribada-project-auto-schedule",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/critical-path/",
        ProjectCriticalPathEndpoint.as_view(),
        name="arribada-project-critical-path",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/wiki-doc/",
        ProjectWikiDocEndpoint.as_view(),
        name="arribada-project-wiki-doc",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/clone/",
        ProjectTemplateCloneEndpoint.as_view(),
        name="arribada-project-clone",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/status/",
        ProjectStatusEndpoint.as_view(),
        name="arribada-project-status",
    ),
    path(
        "workspaces/<str:slug>/project-statuses/",
        WorkspaceProjectStatusesEndpoint.as_view(),
        name="arribada-project-statuses",
    ),
    path(
        "workspaces/<str:slug>/critical-path/",
        WorkspaceCriticalPathEndpoint.as_view(),
        name="arribada-workspace-critical-path",
    ),
    path(
        "workspaces/<str:slug>/adopt-issues/",
        AdoptIssuesEndpoint.as_view(),
        name="arribada-adopt-issues",
    ),
    path(
        "workspaces/<str:slug>/github-inbox/",
        GithubInboxEndpoint.as_view(),
        name="arribada-github-inbox",
    ),
    path(
        "workspaces/<str:slug>/hub-projects/",
        HubProjectsEndpoint.as_view(),
        name="arribada-hub-projects",
    ),
    path(
        "workspaces/<str:slug>/team-sync/",
        TeamSyncEndpoint.as_view(),
        name="arribada-team-sync",
    ),
    path(
        "workspaces/<str:slug>/workload/",
        WorkloadEndpoint.as_view(),
        name="arribada-workload",
    ),
    path(
        "workspaces/<str:slug>/my-work/",
        MyWorkEndpoint.as_view(),
        name="arribada-my-work",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/overview/",
        ProjectOverviewEndpoint.as_view(),
        name="arribada-project-overview",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/team/",
        ProjectTeamEndpoint.as_view(),
        name="arribada-project-team",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/ai-plan/",
        ProjectAiPlanEndpoint.as_view(),
        name="arribada-project-ai-plan",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/apply-plan/",
        ProjectApplyPlanEndpoint.as_view(),
        name="arribada-project-apply-plan",
    ),
    path(
        "workspaces/<str:slug>/ai-settings/",
        WorkspaceAiSettingsEndpoint.as_view(),
        name="arribada-ai-settings",
    ),
    path(
        "workspaces/<str:slug>/task-blueprints/",
        ProjectBlueprintEndpoint.as_view(),
        name="arribada-task-blueprints",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/setup-plan/",
        ProjectSetupPlanEndpoint.as_view(),
        name="arribada-project-setup-plan",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/setup-apply/",
        ProjectSetupApplyEndpoint.as_view(),
        name="arribada-project-setup-apply",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/clean/",
        ProjectCleanEndpoint.as_view(),
        name="arribada-project-clean",
    ),
    path(
        "workspaces/<str:slug>/project-folders/",
        ProjectFoldersEndpoint.as_view(),
        name="arribada-project-folders",
    ),
    path(
        "workspaces/<str:slug>/project-folders/assign/",
        ProjectFolderAssignEndpoint.as_view(),
        name="arribada-project-folder-assign",
    ),
    path(
        "workspaces/<str:slug>/project-folders/<uuid:folder_id>/",
        ProjectFolderDetailEndpoint.as_view(),
        name="arribada-project-folder-detail",
    ),
]
