# Copyright (c) 2026-present Arribada Initiative and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

from django.urls import path

from .views import (
    ProjectProcurementDecisionEndpoint,
    ProjectProcurementEndpoint,
    GithubSyncNowEndpoint,
    GithubTriageEndpoint,
    IssueEffortEndpoint,
    IssueRoleEndpoint,
    ProjectAiSprintTasksEndpoint,
    ProjectPublicTimelineEndpoint,
    PublicTimelineEndpoint,
    WorkspacePublicTimelinesEndpoint,
    ProjectBudgetEndpoint,
    ProjectExpenseDetailEndpoint,
    ProjectExpensesEndpoint,
    WorkspaceCalendarEndpoint,
    WorkspaceCurrencyEndpoint,
    WorkspaceRoleRatesEndpoint,
    AdoptIssuesEndpoint,
    GithubInboxEndpoint,
    ProjectAiDraftEndpoint,
    ProjectBlueprintEndpoint,
    ProjectCleanEndpoint,
    ProjectSetupApplyEndpoint,
    ProjectSetupPlanEndpoint,
    HubProjectsEndpoint,
    MyWorkEndpoint,
    ProjectAiPlanEndpoint,
    ProjectApplyPlanEndpoint,
    ProjectOverviewEndpoint,
    ProjectStatusEndpoint,
    ProjectTeamEndpoint,
    ProjectTemplateCloneEndpoint,
    TeamSyncEndpoint,
    UserTimelineEndpoint,
    WorkloadEndpoint,
    WorkloadTimelineEndpoint,
    WorkspaceAiSettingsEndpoint,
    WorkspaceCriticalPathEndpoint,
    WorkspaceProjectStatusesEndpoint,
    PortfolioEndpoint,
    PortfolioItemsEndpoint,
    ProjectWikiDocEndpoint,
    ProjectAutoScheduleEndpoint,
    ProjectBaselineEndpoint,
    ProjectCriticalPathEndpoint,
    ProjectFolderAssignEndpoint,
    ProjectFolderDetailEndpoint,
    ProjectFoldersEndpoint,
    ProjectProgressEndpoint,
    IssueAllocationEndpoint,
    IssueArtifactsEndpoint,
    ProjectAiDraftItemEndpoint,
    ProjectMilestonesEndpoint,
    WorkspaceDeliverablesEndpoint,
    WorkspaceMyApprovalsEndpoint,
    ProjectRelationsEndpoint,
    ProjectScheduleEndpoint,
)

urlpatterns = [
    path(
        "workspaces/<str:slug>/portfolio/",
        PortfolioEndpoint.as_view(),
        name="arribada-portfolio",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/items/",
        PortfolioItemsEndpoint.as_view(),
        name="arribada-portfolio-items",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/schedule/",
        ProjectScheduleEndpoint.as_view(),
        name="arribada-project-schedule",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/relations/",
        ProjectRelationsEndpoint.as_view(),
        name="arribada-project-relations",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/ai-draft-item/",
        ProjectAiDraftItemEndpoint.as_view(),
        name="arribada-project-ai-draft-item",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/issues/<uuid:issue_id>/allocation/",
        IssueAllocationEndpoint.as_view(),
        name="arribada-issue-allocation",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/issues/<uuid:issue_id>/artifacts/",
        IssueArtifactsEndpoint.as_view(),
        name="arribada-issue-artifacts",
    ),
    path(
        "workspaces/<str:slug>/deliverables/",
        WorkspaceDeliverablesEndpoint.as_view(),
        name="arribada-workspace-deliverables",
    ),
    path(
        "workspaces/<str:slug>/my-approvals/",
        WorkspaceMyApprovalsEndpoint.as_view(),
        name="arribada-workspace-my-approvals",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/milestones/",
        ProjectMilestonesEndpoint.as_view(),
        name="arribada-project-milestones",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/progress/",
        ProjectProgressEndpoint.as_view(),
        name="arribada-project-progress",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/baseline/",
        ProjectBaselineEndpoint.as_view(),
        name="arribada-project-baseline",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/auto-schedule/",
        ProjectAutoScheduleEndpoint.as_view(),
        name="arribada-project-auto-schedule",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/critical-path/",
        ProjectCriticalPathEndpoint.as_view(),
        name="arribada-project-critical-path",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/wiki-doc/",
        ProjectWikiDocEndpoint.as_view(),
        name="arribada-project-wiki-doc",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/clone/",
        ProjectTemplateCloneEndpoint.as_view(),
        name="arribada-project-clone",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/status/",
        ProjectStatusEndpoint.as_view(),
        name="arribada-project-status",
    ),
    path(
        "workspaces/<str:slug>/project-statuses/",
        WorkspaceProjectStatusesEndpoint.as_view(),
        name="arribada-project-statuses",
    ),
    path(
        "workspaces/<str:slug>/critical-path/",
        WorkspaceCriticalPathEndpoint.as_view(),
        name="arribada-workspace-critical-path",
    ),
    path(
        "workspaces/<str:slug>/adopt-issues/",
        AdoptIssuesEndpoint.as_view(),
        name="arribada-adopt-issues",
    ),
    path(
        "workspaces/<str:slug>/github-triage/",
        GithubTriageEndpoint.as_view(),
        name="arribada-github-triage",
    ),
    path(
        "workspaces/<str:slug>/github-inbox/",
        GithubInboxEndpoint.as_view(),
        name="arribada-github-inbox",
    ),
    path(
        "workspaces/<str:slug>/hub-projects/",
        HubProjectsEndpoint.as_view(),
        name="arribada-hub-projects",
    ),
    path(
        "workspaces/<str:slug>/team-sync/",
        TeamSyncEndpoint.as_view(),
        name="arribada-team-sync",
    ),
    path(
        "workspaces/<str:slug>/workload/",
        WorkloadEndpoint.as_view(),
        name="arribada-workload",
    ),
    path(
        "workspaces/<str:slug>/workload-timeline/",
        WorkloadTimelineEndpoint.as_view(),
        name="arribada-workload-timeline",
    ),
    path(
        "workspaces/<str:slug>/my-work/",
        MyWorkEndpoint.as_view(),
        name="arribada-my-work",
    ),
    path(
        "workspaces/<str:slug>/users/<uuid:user_id>/timeline/",
        UserTimelineEndpoint.as_view(),
        name="arribada-user-timeline",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/overview/",
        ProjectOverviewEndpoint.as_view(),
        name="arribada-project-overview",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/team/",
        ProjectTeamEndpoint.as_view(),
        name="arribada-project-team",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/ai-plan/",
        ProjectAiPlanEndpoint.as_view(),
        name="arribada-project-ai-plan",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/apply-plan/",
        ProjectApplyPlanEndpoint.as_view(),
        name="arribada-project-apply-plan",
    ),
    path(
        "workspaces/<str:slug>/ai-settings/",
        WorkspaceAiSettingsEndpoint.as_view(),
        name="arribada-ai-settings",
    ),
    path(
        "workspaces/<str:slug>/task-blueprints/",
        ProjectBlueprintEndpoint.as_view(),
        name="arribada-task-blueprints",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/setup-plan/",
        ProjectSetupPlanEndpoint.as_view(),
        name="arribada-project-setup-plan",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/setup-apply/",
        ProjectSetupApplyEndpoint.as_view(),
        name="arribada-project-setup-apply",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/clean/",
        ProjectCleanEndpoint.as_view(),
        name="arribada-project-clean",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/ai-draft/",
        ProjectAiDraftEndpoint.as_view(),
        name="arribada-project-ai-draft",
    ),
    path(
        "workspaces/<str:slug>/project-folders/",
        ProjectFoldersEndpoint.as_view(),
        name="arribada-project-folders",
    ),
    path(
        "workspaces/<str:slug>/project-folders/assign/",
        ProjectFolderAssignEndpoint.as_view(),
        name="arribada-project-folder-assign",
    ),
    path(
        "workspaces/<str:slug>/project-folders/<uuid:folder_id>/",
        ProjectFolderDetailEndpoint.as_view(),
        name="arribada-project-folder-detail",
    ),
    path(
        "workspaces/<str:slug>/calendar/",
        WorkspaceCalendarEndpoint.as_view(),
        name="arribada-workspace-calendar",
    ),
    path(
        "workspaces/<str:slug>/role-rates/",
        WorkspaceRoleRatesEndpoint.as_view(),
        name="arribada-workspace-role-rates",
    ),
    path(
        "workspaces/<str:slug>/currency/",
        WorkspaceCurrencyEndpoint.as_view(),
        name="arribada-workspace-currency",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/expenses/",
        ProjectExpensesEndpoint.as_view(),
        name="arribada-project-expenses",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/expenses/<uuid:expense_id>/",
        ProjectExpenseDetailEndpoint.as_view(),
        name="arribada-project-expense-detail",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/budget/",
        ProjectBudgetEndpoint.as_view(),
        name="arribada-project-budget",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/procurement/",
        ProjectProcurementEndpoint.as_view(),
        name="arribada-project-procurement",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/procurement/<uuid:request_id>/",
        ProjectProcurementDecisionEndpoint.as_view(),
        name="arribada-project-procurement-decision",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/issues/<uuid:issue_id>/role/",
        IssueRoleEndpoint.as_view(),
        name="arribada-issue-role",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/issues/<uuid:issue_id>/effort/",
        IssueEffortEndpoint.as_view(),
        name="arribada-issue-effort",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/github-sync/",
        GithubSyncNowEndpoint.as_view(),
        name="arribada-project-github-sync",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/ai-sprint-tasks/",
        ProjectAiSprintTasksEndpoint.as_view(),
        name="arribada-project-ai-sprint-tasks",
    ),
    path(
        "workspaces/<str:slug>/projects/<uuid:project_id>/public-timeline/",
        ProjectPublicTimelineEndpoint.as_view(),
        name="arribada-project-public-timeline",
    ),
    path(
        "workspaces/<str:slug>/public-timelines/",
        WorkspacePublicTimelinesEndpoint.as_view(),
        name="arribada-workspace-public-timelines",
    ),
    # No workspace slug and no project id in this path on purpose: the anchor is
    # the only credential, so nothing the caller supplies may widen what is read.
    path(
        "public/timeline/<str:anchor>/",
        PublicTimelineEndpoint.as_view(),
        name="arribada-public-timeline",
    ),
]
