# Generated by Django 4.2.30 on 2026-08-01 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0121_alter_estimate_type'),
        ('arribada', '0014_merge_project_lead_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteammember',
            name='days_per_week',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='projectteammember',
            name='leave',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='WorkspaceRoleRate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(max_length=80)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=7, max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arribada_role_rates', to='db.workspace')),
            ],
            options={
                'db_table': 'arribada_role_rate',
                'ordering': ('role',),
                'unique_together': {('workspace', 'role')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceNonWorkingDay',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arribada_non_working_days', to='db.workspace')),
            ],
            options={
                'db_table': 'arribada_non_working_day',
                'ordering': ('date',),
                'unique_together': {('workspace', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('hardware', 'Hardware & components'), ('travel', 'Travel'), ('field', 'Field trip'), ('services', 'Services & subcontracting'), ('shipping', 'Shipping & customs'), ('other', 'Other')], default='other', max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('planned', models.BooleanField(default=True)),
                ('incurred_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arribada_expenses', to='db.project')),
            ],
            options={
                'db_table': 'arribada_project_expense',
                'ordering': ('-incurred_on', '-created_at'),
                'indexes': [models.Index(fields=['project', 'planned'], name='arribada_pr_project_b6773d_idx')],
            },
        ),
    ]
