# Generated by Django 4.2.30 on 2026-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arribada', '0015_work_calendar_rates_and_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectschedule',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projectschedule',
            name='budget_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
