# Generated by Django 4.2.30 on 2026-08-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0121_alter_estimate_type'),
        ('arribada', '0016_project_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('hardware', 'Hardware & components'), ('travel', 'Travel'), ('field', 'Field trip'), ('services', 'Services & subcontracting'), ('shipping', 'Shipping & customs'), ('other', 'Other')], default='other', max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('justification', models.TextField(blank=True, default='')),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='arribada.projectexpense')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arribada_procurement', to='db.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'arribada_procurement_request',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['project', 'status'], name='arribada_pr_project_45208c_idx')],
            },
        ),
    ]
