# Generated by Django 4.2.30 on 2026-08-01 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0121_alter_estimate_type'),
        ('arribada', '0017_procurement_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceCurrencySettings',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('display_currency', models.CharField(blank=True, default='', max_length=3)),
                ('eur_gbp_rate', models.DecimalField(decimal_places=6, default=0.85, max_digits=12)),
                ('rate_captured_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arribada_currency_settings', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace currency settings',
                'verbose_name_plural': 'Workspace currency settings',
                'db_table': 'arribada_currency_settings',
            },
        ),
    ]
