# Generated by Django 4.2.30 on 2026-08-03 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.arribada.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arribada', '0025_cycle_scope_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPublicTimeline',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('anchor', models.CharField(db_index=True, default=plane.arribada.models.public_anchor, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arribada_public_timelines', to='db.project')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project public timeline',
                'verbose_name_plural': 'Project public timelines',
                'db_table': 'arribada_project_public_timeline',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='projectpublictimeline',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('project',), name='arribada_one_live_public_timeline_per_project'),
        ),
    ]
