# Generated by Django 4.2.30 on 2026-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arribada', '0027_issueeffort'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectschedule',
            name='allow_add_items',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectschedule',
            name='allow_edit_others',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectschedule',
            name='timeline_locked',
            field=models.BooleanField(default=False),
        ),
    ]
